swagger: '2.0'
info:
  description: API documentation for Argent Bank
  version: "1.0.0"
  title: Argent Bank API
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/me:
    get:
      summary: Get user profile
      description: Retrieve the profile of the authenticated user
      responses:
        200:
          description: Successful response
        401:
          description: Unauthorized
  /transactions:
    get:
      summary: Get all transactions for the current month
      description: Retrieve all transactions for the current month, grouped by account
      responses:
        200:
          description: Successful response
        401:
          description: Unauthorized
  /transactions/{id}:
    get:
      summary: Get a transaction by ID
      description: Retrieve a transaction by its ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful response
        404:
          description: Transaction not found
        401:
          description: Unauthorized
    put:
      summary: Update a transaction by ID
      description: Update a transaction by its ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - in: body
          name: transaction
          description: Transaction object
          schema:
            type: object
            properties:
              amount:
                type: number
              type:
                type: string
              description:
                type: string
      responses:
        200:
          description: Transaction updated
        400:
          description: Bad request
        404:
          description: Transaction not found
        401:
          description: Unauthorized
    delete:
      summary: Delete a transaction by ID
      description: Delete a transaction by its ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        204:
          description: Transaction deleted
        404:
          description: Transaction not found
        401:
          description: Unauthorized
  /transactions/details/{id}:
    get:
      summary: Get transaction details by ID
      description: Retrieve the details of a transaction by its ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Successful response
        404:
          description: Transaction not found
        401:
          description: Unauthorized