swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/{userId}/transactions:
    parameters:
      - name: userId
        in: path
        description: The ID of the user
        required: true
        type: string
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Current month's transactions
      description: API to retrieve transactions for the current month, grouped by account
      parameters:
        - name: month
          in: query
          description: Month for which to retrieve transactions (YYYY-MM)
          required: false
          type: string
          default: The current month
      responses:
        "200":
          description: Transactions successfully retrieved, grouped by account
          schema:
            type: array
            items:
              $ref: "#/definitions/AccountTransactions"
        "400":
          description: Invalid fields
        "401":
          description: Unauthorized user
        "404":
          description: Invalid user ID
        "500":
          description: Internal server error
  /user/transaction/{transactionId}:
    parameters:
      - name: transactionId
        in: path
        description: The ID of the transaction
        required: true
        type: string
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction details
      description: API to retrieve details of a specific transaction
      produces:
        - application/json
      responses:
        "200":
          description: Transaction successfully retrieved
          schema:
            $ref: "#/definitions/Transaction"
        "401":
          description: Unauthorized user
        "404":
          description: Invalid transaction ID
        "500":
          description: Internal server error
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update a transaction
      description: API to update transaction information (only category and note can be modified)
      parameters:
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: "#/definitions/EditTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction successfully updated
          schema:
            $ref: "#/definitions/Transaction"
        "400":
          description: Invalid fields
        "401":
          description: Unauthorized user
        "500":
          description: Internal server error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete transaction information
      description: API to delete information (such as note or category) from a transaction without deleting the transaction itself
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Information to delete (such as note or category)
          required: true
          schema:
            $ref: "#/definitions/DeleteTransactionInfo"
      responses:
        "200":
          description: Transaction information successfully deleted
        "400":
          description: Invalid fields
        "401":
          description: Unauthorized user
        "404":
          description: Invalid transaction ID
        "500":
          description: Internal server error
definitions:
  AccountTransactions:
    type: object
    properties:
      accountId:
        type: string
      transactions:
        type: array
        items:
          $ref: "#/definitions/Transaction"
  Transaction:
    type: object
    properties:
      id:
        type: string
      amount:
        type: number
      date:
        type: string
        format: date-time
      category:
        type: string
      note:
        type: string
  EditTransaction:
    type: object
    properties:
      category:
        type: string
      note:
        type: string
  DeleteTransactionInfo:
    type: object
    properties:
      category:
        type: string
      note:
        type: string